### ISSUE TITLE
Cannot read property 'setState' of null

### ISSUE THREAD

**Issue by mancoxu** [Broltes/react-touch-loader#10]
![image](https://user-images.githubusercontent.com/15724205/30019404-13b88f8c-9193-11e7-9b6a-7dc2f7cb42d5.png)
![image](https://user-images.githubusercontent.com/15724205/30019420-1f4d2100-9193-11e7-9da7-c1dd61fc8930.png)
![image](https://user-images.githubusercontent.com/15724205/30019437-2e353b3a-9193-11e7-9338-39bafc95260e.png)
请查看下， 更新后v1.1.1后报错 'setState of null ' ， 谢谢。
 是点击onLoadMore 方法时
我报的错和上个提issue的同学应该是一样的，我的语法没有错误，请帮忙查看下

**Comment by Broltes** [comment]
你好，我发布了1.1.2

**Comment by mancoxu** [comment]
多谢～～
