### ISSUE TITLE
使用滚动加载第一次必须要手动点击吗？

### ISSUE THREAD

**Issue by juniorselk** [Broltes/react-touch-loader#12]
第一次点击以后才可以滚动加载吗？而且onLoadMore的函数添加的请求必须要设置定时器来执行吗？

**Comment by Broltes** [comment]
默认不需要点击，滚动到底部自动加载更多。定时器只是demo里用来模拟异步请求，正常不需要的。

**Comment by juniorselk** [comment]
[
![image](https://user-images.githubusercontent.com/25118641/31757996-2b4f4528-b4de-11e7-8175-61c8bd34d23d.png)
](url)
initializing的设置与Demo一致，more是请求的函数，现在第一次是需要点击的，而且滚动到底部自动加载更多动画会出来，但不会发送请求

**Comment by juniorselk** [comment]
@Broltes 作者你好，请问滚动到底部不会自动发送请求并且不会执行加载动画关闭的函数，是什么原因？
