### ISSUE TITLE
怎么让他在下拉到最底部的时候自动加载而不是点击“加载更多”才能进行加载呢

### ISSUE THREAD

**Issue by mvpdream** [Broltes/react-touch-loader#2]
怎么让他在下拉到最底部的时候自动加载而不是点击“加载更多”才能进行加载呢

**Comment by Chaunjie** [comment]
@mvpdream 你可以试试这个，前几个月我加了一个方法只要给Tloader固定住高度就可以了
![image](https://cloud.githubusercontent.com/assets/12093709/21567498/8888d32c-cee7-11e6-89c2-62ce2343f7fe.png)
![image](https://cloud.githubusercontent.com/assets/12093709/21567505/93606bca-cee7-11e6-9ccc-c780dfe04da2.png)

**Comment by Broltes** [comment]
@mvpdream 不好意思，之前添加了滚动到底部自动加载的功能，live demo更新了，但是还没有发布到npm。我刚刚发布了支持此功能的 1.1.0版本，请你更新到这个版本试一下。感谢 @Chaunjie，思路与你一致
