### ISSUE TITLE
如果加载失败了会有什么提示的吗？

### ISSUE THREAD

**Issue by xiaozhouwu** [Broltes/react-touch-loader#5]
如果在下拉刷新或者加载更多的网络请求中由于网络环境或者后台的原因导致无法加载到数据，会有什么提示吗？有没有做错误处理的？

**Comment by xiaozhouwu** [comment]
因为没有在readme中看到有这方面的描述

**Comment by Broltes** [comment]
@xiaozhouwu 下拉刷新的onRefresh回调里有 resolve, reject两个参数，可以分别在你加载成功和失败时调用。
加载更多类似，但是只有一个resolve供你数据加载结束时调用，因为加载更多成功或失败时ui效果一致。
具体建议你参考demo的源码：
