### ISSUE TITLE
animationEnd为什么无法触发？

### ISSUE THREAD

**Issue by xiaozhouwu** [Broltes/react-touch-loader#6]
```
<Tloader onRefresh={this.refresh}>
       <GoodList goodListData={goodListData} />
</Tloader>
```
下拉刷新的时候发现onAnimationEnd绑定的animationEnd函数无法触发，导致刷新成功的提示信息无法隐藏。请问这是什么原因？
![github](https://cloud.githubusercontent.com/assets/21081809/26095459/4930999c-3a50-11e7-9267-dabdcc3c199b.png)

**Comment by Broltes** [comment]
@xiaozhouwu 从这些信息我不能判断问题的原因。建议你尝试：
1. 用出现问题的设备访问 [demo](https://broltes.github.io/tloader) 看是否仍有该问题
2. 如果demo也有问题，请告诉我该设备的系统及其版本和设备的品牌型号
3. 如果demo没有问题，尝试检查tloader是否为固定了高度的滚动区域

**Comment by xiaozhouwu** [comment]
`tloader`组件是已经固定了高度的，其它的一切都正常，包括滚动，下拉刷新。我看了组件的源代码，调试的时候发现代码`onAnimationEnd={this.animationEnd}>`中的`animationEnd`并没有执行。demo是没有问题的，调试是在最新版的chrome，不知何故。

用dom绑定就可以了~~~~
```
componentDidMount() {
        document.getElementsByClassName('tloader')[0].addEventListener('animationend',this.animationEnd);
    },
```
比较郁闷

**Comment by Broltes** [comment]
这个很抱歉，我暂时也没有思路，等有新发现我们再继续在这里讨论吧～
