### ISSUE TITLE
Cannot read property 'setState' of null

### ISSUE THREAD

**Issue by cxylys** [Broltes/react-touch-loader#8]
loadMore(resolve){
      
		setTimeout(()=>{
			var count = this.state.count;
			this.setState({
				count: count+5,
			});
            this.setState({news:NewsData.slice(0,this.state.count)});
		    this.setState({
			    hasMore: count>0 && count<50
	        });
		    resolve();
		},2e3);
    }

<Tloader
                onLoadMore={this.loadMore.bind(this)}
                hasMore={hasMore}
                initializing = {initializing}
            >
                <MNewsList  newsList={news} /> 
         
            </Tloader>]([url]([url](url)))
![image](https://user-images.githubusercontent.com/3087711/29308219-8b89c2ae-81d7-11e7-83fb-e34048670c68.png)

点击尾部加载更多不知为啥一直报 Cannot read property 'setState' of null,

**Comment by liuguanhua** [comment]
loadMore需在constructor中使用bind绑定this
